### ISSUE TITLE
Fails at Publish to Hex.pm

### ISSUE THREAD

**Issue by manuelgeek** [erlangpack/github-action#3]
Stack trace below;

Run erlangpack/github-action@v1
/usr/bin/docker run --name e5c354eb3277c436044c581414637db269ca1_8a3eee --label 1e5c35 --workdir /github/workspace --rm -e HEX_API_KEY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ex_pesa/ex_pesa":"/github/workspace" 1e5c35:4eb3277c436044c581414637db269ca1
===> Fetching rebar3_hex v6.10.0
===> Downloaded package, caching at /github/home/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.10.0.tar
===> Fetching hex_core v0.6.9
===> Downloaded package, caching at /github/home/.cache/rebar3/hex/hexpm/packages/hex_core-0.6.9.tar
===> Fetching verl v1.0.2
===> Downloaded package, caching at /github/home/.cache/rebar3/hex/hexpm/packages/verl-1.0.2.tar
===> Analyzing applications...
===> Compiling verl
===> Analyzing applications...
===> Compiling hex_core
===> Analyzing applications...
===> Compiling rebar3_hex
home/.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_user.erl:246: Warning: crypto:block_encrypt/4 is deprecated and will be removed in OTP 24; use use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
home/.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_user.erl:256: Warning: crypto:block_decrypt/4 is deprecated and will be removed in OTP 24; use use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead

===> Verifying dependencies...
===> Verifying dependencies...
Select application(s):------------A) All[1-0] or (A)ll  ("A")> ===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`

**Comment by OldhamMade** [comment]
Any news on a fix for this?

**Comment by mworrell** [comment]
This was a problem in rebar3 and has been resolved there.

Be sure that the OTP version is at least 23, as rebar3 doesn't support OTP 22 anymore (as of this date).

For this plugin I am setting the OTP version to 24 (see #4 )
