### ISSUE TITLE
Unable to publish to private

### ISSUE THREAD

**Issue by himangshuj** [erlangpack/github-action#8]
![Screenshot 2023-09-27 at 2 26 15 PM](https://github.com/erlangpack/github-action/assets/391484/6bf2f9ee-43f7-40eb-88fa-8ea5d659ec4f)
Getting an error ```===> publish can not continue, no apps were found.```
Things work locally
```mix hex.publish --organization hamilton_practice --replace```

**Comment by mworrell** [comment]
@ddeboer any idea?

**Comment by himangshuj** [comment]
Happy to help in fixing, if i get some guidance

**Comment by onurozgurozkan** [comment]
I got the same error. 

https://github.com/hipcall/hipcall_openai/actions/runs/9642956892/job/26591897595

**Comment by ddeboer** [comment]
This action [uses rebar3 (not hex)](https://github.com/erlangpack/github-action/blob/master/entrypoint.sh#L8). Could that be causing the difference?

**Comment by onurozgurozkan** [comment]
> This action [uses rebar3 (not hex)](https://github.com/erlangpack/github-action/blob/master/entrypoint.sh#L8). Could that be causing the difference?

@ddeboer thank you for quick reply. It is my bad. I didn't check the source code.
 I've just write Github action for hex (not rebar3). I put the link here,  https://github.com/hipcall/github-action-publish-hex/
Regards.
